package com.wonders.asset.dao.impl;

import java.sql.Timestamp;
import java.util.Date;
import java.util.HashMap;

import com.wonders.asset.base.dao.impl.BaseDaoImpl;
import com.wonders.asset.dao.SparePartsDao;
import com.wonders.asset.model.SpareParts;

public class SparePartsDaoImpl extends BaseDaoImpl<SpareParts, String> implements SparePartsDao{

	
	public SparePartsDaoImpl() {
		super(SpareParts.class);
		
	}

	/**
	 * 同步数据插入
	 */
	@Override
	public void syncInsertData(Date startDate, Date endDate) {
		HashMap parameter = new HashMap();
		String whereSql = "";
		if(startDate!=null){
			whereSql += " AND MODIFY_TIME >= :startDate";
			parameter.put("startDate",startDate);
		}
		if(endDate!=null){
			whereSql += " AND MODIFY_TIME <= :endDate";
			parameter.put("endDate",endDate);
		}
		String sql = "INSERT INTO  T_SPARE_PARTS  T" +
				"(" +
				"ID,PROJECT_NAME,PROJECT_NO,PROJECT_CONTRACT_NO,SPARE_ASSET_NO,SPARE_ASSET_DESCRIPTION," +
				"AT1,AT2,AT3,UNIT_CODE,ASSET_QTY,FIN_GZXH,PRODUCT_AREA,MANUFACTURER,SUPPLIER,LEAVE_FACTORY," +
				"SUPPLY_DATE,OWNERSHIP_UNIT,OWNERSHIP_UNIT_NAME,USE_UNIT,USE_UNIT_NAME,MAINTAIN_DEPART," +
				"MAINTAIN_DEPART_NAME,LOC_LINE,LOCATION_CODE,TRANSFER_DATE,DESIGN_USE_LIFE,WARRANTY_PERIOD," +
				"FACTORY_PRICE,CONTRACT_PRICE,ORIGINAL_VALUE,HAVE_LIST,EQUIP_LIST,COMPLETE_TRANS_ASSET_TYPE," +
				"OPERATE_PROJECT_ASSET,OPERATE_PROJECT_ASSET_DATE,OPERATE_PROJECT_ASSET_ACCOUNT,PROJECT_APP_DOC_NO," +
				"REMARKS,VERSION,CREATE_TIME,MODIFY_TIME" +
				")" +
				" SELECT " +
				" SEQ_NO,PROJECT_NAME,PROJECT_NO,PROJECT_CONTRACT_NO,SPARE_ASSET_NO,SPARE_ASSET_DESCRIPTION," +
				"AT1,AT2,AT3,UNIT_CODE,ASSET_QTY,FIN_GZXH,PRODUCE_AREA,MANUFACTURER,SUPPLIER,LEAVE_FACTORY," +
				"SUPPLY_DATE,OWNERSHIP_UNIT,OWNERSHIP_UNIT_NAME,USE_UNIT," +
				"USE_UNIT_NAME,MAINTAIN_DEPART,MAINTAIN_DEPART_NAME,LOC_LINE,LOCATION_CODE,TRANSFER_DATE," +
				"DESIGN_USE_LIFE,WARRANTY_PERIOD,FACTORY_PRICE,CONTRACT_PRICE,ORIGINAL_VALUE,HAVE_LIST,EQUIP_LIST," +
				"COMPLETE_TRANS_ASSET_TYPE,OPERATE_PROJECT_ASSET,OPERATE_PROJECT_ASSET_DATE," +
				"OPERATE_PROJECT_ASSET_ACCOUNT,PROJECT_APP_DOC_NO,REMARK,VERSION,CREATE_TIME," +
				"MODIFY_TIME" +
				" FROM JV_SPARE_PARTS J" +
				" WHERE NOT EXISTS(SELECT 1 FROM T_SPARE_PARTS WHERE SPARE_ASSET_NO = J.SPARE_ASSET_NO) "+whereSql;
		getHibernateTemplate().getSessionFactory().getCurrentSession().createSQLQuery(sql).setProperties(parameter).executeUpdate();   
	}

	/**
	 * 同步数据更新
	 */
	@Override
	public void syncUpdateData(Date startDate, Date endDate) {
		HashMap parameter = new HashMap();
		String whereSql = "";
		if(startDate!=null){
			whereSql += " AND MODIFY_TIME >= :startDate";
			parameter.put("startDate",startDate);
		}
		if(endDate!=null){
			whereSql += " AND MODIFY_TIME <= :endDate";
			parameter.put("endDate",endDate);
		}
		String sql = "UPDATE T_SPARE_PARTS T" +
					" SET(" +
					"PROJECT_NAME,PROJECT_NO,PROJECT_CONTRACT_NO,SPARE_ASSET_NO,SPARE_ASSET_DESCRIPTION," +
					"AT1,AT2,AT3,UNIT_CODE,ASSET_QTY,FIN_GZXH,PRODUCT_AREA,MANUFACTURER,SUPPLIER,LEAVE_FACTORY," +
					"SUPPLY_DATE,OWNERSHIP_UNIT,OWNERSHIP_UNIT_NAME,USE_UNIT,USE_UNIT_NAME,MAINTAIN_DEPART," +
					"MAINTAIN_DEPART_NAME,LOC_LINE,LOCATION_CODE,TRANSFER_DATE,DESIGN_USE_LIFE,WARRANTY_PERIOD," +
					"FACTORY_PRICE,CONTRACT_PRICE,ORIGINAL_VALUE,HAVE_LIST,EQUIP_LIST,COMPLETE_TRANS_ASSET_TYPE," +
					"OPERATE_PROJECT_ASSET,OPERATE_PROJECT_ASSET_DATE,OPERATE_PROJECT_ASSET_ACCOUNT,PROJECT_APP_DOC_NO," +
					"REMARKS,VERSION,CREATE_TIME,MODIFY_TIME" +
					")=(" +
					"SELECT " +
					"PROJECT_NAME,PROJECT_NO,PROJECT_CONTRACT_NO,SPARE_ASSET_NO,SPARE_ASSET_DESCRIPTION,AT1,AT2,AT3," +
					"UNIT_CODE,ASSET_QTY,FIN_GZXH,PRODUCE_AREA,MANUFACTURER,SUPPLIER,LEAVE_FACTORY,SUPPLY_DATE,OWNERSHIP_UNIT," +
					"OWNERSHIP_UNIT_NAME,USE_UNIT,USE_UNIT_NAME,MAINTAIN_DEPART,MAINTAIN_DEPART_NAME,LOC_LINE,LOCATION_CODE," +
					"TRANSFER_DATE,DESIGN_USE_LIFE,WARRANTY_PERIOD,FACTORY_PRICE,CONTRACT_PRICE,ORIGINAL_VALUE,HAVE_LIST," +
					"EQUIP_LIST,COMPLETE_TRANS_ASSET_TYPE,OPERATE_PROJECT_ASSET,OPERATE_PROJECT_ASSET_DATE,OPERATE_PROJECT_ASSET_ACCOUNT," +
					"PROJECT_APP_DOC_NO,REMARK,VERSION,CREATE_TIME,MODIFY_TIME" +
					" FROM JV_SPARE_PARTS J" +
					" WHERE J.SPARE_ASSET_NO = T.SPARE_ASSET_NO" +
					")" +
					" WHERE EXISTS(SELECT 1 FROM JV_SPARE_PARTS WHERE SPARE_ASSET_NO = T.SPARE_ASSET_NO) "+whereSql;
		getHibernateTemplate().getSessionFactory().getCurrentSession().createSQLQuery(sql).setProperties(parameter).executeUpdate();		
	}

}
